
[profile.default]
src = 'contracts'
out = 'out'
cache_path = 'cache_foundry'
libs = ['lib']

solc = '0.8.16'
via_ir = true
optimizer = true
optimizer_runs = 100000

[rpc_endpoints]
mainnet = "https://eth-rpc.gateway.pokt.network"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config