
[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']

solc = '0.8.16'
via_ir = true
optimizer = true
optimizer_runs = 100000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config